### PR TITLE
Patience.fe dev

### PR DESCRIPTION
**Pull request by ahmad-cod**
issue: #257 Threads component Main Message

### CODE REVIEW

**Comment by ahmad-cod** [comment]
issue: #257  
reviewer: @mrkendrick

**Review by mrkendrick — CHANGES_REQUESTED** [review]
Sync your code, don't merge to main

**Comment by ahmad-cod** [comment]
My PR is now ready
I've edited the base to be dev,

**Comment by ahmad-cod** [comment]
Linked issues #257 Thread Component: Main Message.
Assignees: @ahmad-cod

**Pull request closed without merging**
